### ISSUE TITLE
Module not found: Can't resolve '@babel/runtime/helpers/builtin/assertThisInitialized'

### ISSUE THREAD

**Issue by nakagit** [mnemonic-no/act-frontend#1]
Hi!

I executed '`yarn install`', but error message(s) were popped out as following:
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'

Then I run the following command:
```
npm install
npm start
```

Unfortunately, I've got following error message:
Failed to compile.

./node_modules/@material-ui/core/ButtonBase/TouchRipple.js
Module not found: Can't resolve '@babel/runtime/helpers/builtin/assertThisInitialized' in '/opt/act-frontend/node_modules/@material-ui/core/ButtonBase'

Please have a look my screenshot.
![npm_start_error](https://user-images.githubusercontent.com/10558255/53246000-bcdb8780-36f2-11e9-9d13-74dd0ca194a2.png)

Kind regards,
Yuki

**Comment by nakagit** [comment]
Because '`yarn install`' command didn't work well, I tried to run '`npm install`'.
But, I encountered following error message:
Module not found: Can't resolve '@babel/runtime/helpers/buitin/xxxxxxxx

Then, I executed following command:
`npm install @babel/runtime@7.0.0-beta.55`
(Compile has completed without any errors.)
(I referred [https://forums.meteor.com/t/solved-cannot-find-module-babel-runtime-helpers-builtin-objectspread-after-update-meteor-to-1-6-1-1/43034](url).)

Then, I run:
`npm start`

After above command, I finally saw the ACT frontend as following:
![act-frontend_error](https://user-images.githubusercontent.com/10558255/53263166-f2489b00-371b-11e9-9360-84f6a1703d3c.png)


However, I found '**Error loading required data**' error message at the top of left corner.

So far, I didn't see any wired/error messages at terminal window.

I'm almost there, could you please help me out?


Kindest regards,
Yuki

**Comment by frbor** [comment]
Hi Yuki, 

for yarn it seems like there is something wrong with your yarn installation. I found some references to the same problem here: [https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install](https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install).

Can you see if there are any directions there that might help you regarding the yarn issue?

However it seems like you have managed to complete the build using npm. 

"Error loading required data" means that your client was unable to get the data from the backend. There could be many reasons for this, but you need to make sure that you have installed the [act-platform](https://github.com/mnemonic-no/act-platform) and [bootstrapped](https://github.com/mnemonic-no/act-bootstrap) it with the datamodel. You also need to make sure that you points the "apiUrl" in "src/config.js" in the act-frontend to you act-platform, prior to the build (using yarn or npm).

**Comment by nakagit** [comment]
Hi frbor,

Thanks for your help.

According to yarn, I successfuly installed yarn with 
https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install.

But, I still have the same error message, '**Error loading required data**'.

I didn't install bootstrapped, 'https://github.com/mnemonic-no/act-bootstrap'. So, installed bootstrapped.
Then I run './act-bootstrap.sh 1 http://localhost:8080', but it failed with following errors:

Logging to bootstrap.log.36175
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f3d8df9d400>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /v1/objectType (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3d8df9d400>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bootstrap/act-bootstrap.py", line 143, in <module>
    client, object_types_filename=args.object_types_filename)
  File "bootstrap/act-bootstrap.py", line 66, in create_object_types
    for object_type in client.get_object_types()]
  File "/usr/local/lib/python3.7/dist-packages/act/helpers.py", line 221, in get_object_types
    self.api_get("v1/objectType"),
  File "/usr/local/lib/python3.7/dist-packages/act/base.py", line 216, in api_get
    return self.api_request("GET", uri, params=params)
  File "/usr/local/lib/python3.7/dist-packages/act/base.py", line 194, in api_request
    **kwargs
  File "/usr/local/lib/python3.7/dist-packages/act/base.py", line 56, in request
    **requests_kwargs
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /v1/objectType (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3d8df9d400>: Failed to establish a new connection: [Errno 111] Connection refused'))
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f5808e5de48>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /v1/fact (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5808e5de48>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bootstrap/misp-threat-actors.py", line 132, in <module>
    add_to_act(client, ta)
  File "bootstrap/misp-threat-actors.py", line 101, in add_to_act
    .source("threatActor", name)\
  File "/usr/local/lib/python3.7/dist-packages/act/fact.py", line 381, in add
    return self.__add_fact()
  File "/usr/local/lib/python3.7/dist-packages/act/fact.py", line 402, in __add_fact
    fact = self.api_post("v1/fact", **params)["data"]
  File "/usr/local/lib/python3.7/dist-packages/act/base.py", line 202, in api_post
    return self.api_request("POST", uri, json=kwargs)
  File "/usr/local/lib/python3.7/dist-packages/act/base.py", line 194, in api_request
    **kwargs
  File "/usr/local/lib/python3.7/dist-packages/act/base.py", line 56, in request
    **requests_kwargs
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /v1/fact (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5808e5de48>: Failed to establish a new connection: [Errno 111] Connection refused'))
Traceback (most recent call last):
  File "bootstrap/mitre-attack.py", line 216, in <module>
    attack_software_raw = mediawiki_ask(MITRE_ATTACK_URL, "[[Category:Software]]", MITRE_ALL_PROPERTIES)
  File "bootstrap/mitre-attack.py", line 182, in mediawiki_ask
    r = requests.get(url, params = payload, verify = False).json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f9fa51d80b8>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /v1/fact (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9fa51d80b8>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bootstrap/fireeye-carbanak.py", line 81, in <module>
    carbanak_report(client)
  File "bootstrap/fireeye-carbanak.py", line 47, in carbanak_report
    .destination("tool", "carbanak")\
  File "/usr/local/lib/python3.7/dist-packages/act/fact.py", line 381, in add
    return self.__add_fact()
  File "/usr/local/lib/python3.7/dist-packages/act/fact.py", line 402, in __add_fact
    fact = self.api_post("v1/fact", **params)["data"]
  File "/usr/local/lib/python3.7/dist-packages/act/base.py", line 202, in api_post
    return self.api_request("POST", uri, json=kwargs)
  File "/usr/local/lib/python3.7/dist-packages/act/base.py", line 194, in api_request
    **kwargs
  File "/usr/local/lib/python3.7/dist-packages/act/base.py", line 56, in request
    **requests_kwargs
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /v1/fact (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9fa51d80b8>: Failed to establish a new connection: [Errno 111] Connection refused'))


As for the "apiUrl" in "src/config.js", I couldn't find config.js. 
However I found config.json at /opt/act-frontend/src/config.json as following:
![190227-0002](https://user-images.githubusercontent.com/10558255/53452370-75dbf200-3a64-11e9-9977-7818b60150ad.png)


In order to solve this issue, I'll get any information, please let me know.


Kind regards,
Yuki

**Comment by frbor** [comment]
Hi,

I think you are close. However, the default port for the platform (specified in application.properties.localhost or a copy of that file) is 8888, so unless you have changed this, you need to change the url to "http://localhost:8888" both in the src/config.js at the frontend and when bootstrap'ing.

best regards,
     Fredrik

**Comment by nakagit** [comment]
Thank you for your support.

I did what you mentioned, but I still have some errors as following:
![190301-0002](https://user-images.githubusercontent.com/10558255/53596454-1fe18880-3be3-11e9-84e7-ed1f1b205564.png)


root@kali2018:/opt/act-bootstrap# `./act-bootstrap.sh 1 http://localhost:8888`
Logging to bootstrap.log.38478
Traceback (most recent call last):
  File "bootstrap/mitre-attack.py", line 216, in <module>
    attack_software_raw = mediawiki_ask(MITRE_ATTACK_URL, "[[Category:Software]]", MITRE_ALL_PROPERTIES)
  File "bootstrap/mitre-attack.py", line 182, in mediawiki_ask
    r = requests.get(url, params = payload, verify = False).json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

root@kali2018:/opt/act-platform/executable# `java -Dapplication.properties.file=/opt/act-platform/executable/application.properties.localhost -jar /opt/act-platform/executable/target/act-platform-0.0.1-SNAPSHOT.jar guice module=no.mnemonic.act.platform.rest.RestModule module=no.mnemonic.act.platform.service.ServiceModule`
**
Bootstrap 0.0.1-SNAPSHOT
**
Fri Mar 01 05:24:23 JST 2019 - An unknown exception occurred:
org.jboss.resteasy.spi.DefaultOptionsMethodException: RESTEASY003655: No resource method found for options, return OK with Allow header
	at org.jboss.resteasy.core.registry.SegmentNode.match(SegmentNode.java:483)
	at org.jboss.resteasy.core.registry.SegmentNode.match(SegmentNode.java:174)
	at org.jboss.resteasy.core.registry.RootNode.match(RootNode.java:43)
	at org.jboss.resteasy.core.registry.RootClassNode.match(RootClassNode.java:48)
	at org.jboss.resteasy.core.ResourceMethodRegistry.getResourceInvoker(ResourceMethodRegistry.java:442)
	at org.jboss.resteasy.core.SynchronousDispatcher.getInvoker(SynchronousDispatcher.java:304)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:225)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:139)
	at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:358)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:142)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:219)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:227)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

Any suggestion to resolve this issue?

Kind regards,
Yuki

**Comment by ko-mueller** [comment]
Hi!

Those are two different errors.

1. Something went wrong during execution of the bootstrap script while fetching data from MITRE. I don't have knowledge about that script. Fredrik can hopefully help you with that.
2. The error message displayed from the platform is related to cross origin requests (CORS). If you run both the platform and the frontend on localhost the browser won't allow requests to the platform because they don't have the same origin (more specifically different ports on localhost). This needs to be handled in the platform code and I'll try to prioritize it early next week.

Kind regards,
Konstantin

**Comment by ko-mueller** [comment]
Hi!

I've implemented CORS support in the newest version of the platform. With that the frontend should be able to communicate directly with the API.

Can you please verify if it now works for you?

Kind regards,
Konstantin

**Comment by nakagit** [comment]
Hi!

Thank you so much. The problem was fixed.  :)
![190308-0003](https://user-images.githubusercontent.com/10558255/54001585-1c27a600-418f-11e9-8384-5840bbdaac50.png)


Kind regards,
Yuki
